name: "Test and apply google big query configuration"

on: push

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform Format Check
        uses: dflook/terraform-fmt@v2
      - name: Terraform Validate
        uses: dflook/terraform-validate@v2
      - name: Decode OIDC token
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=google-cloud")
          echo $TOKEN | cut -d. -f2 | base64 --decode
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: "projects/937748189510/locations/global/workloadIdentityPools/github-actions-benchmark/providers/github"
          service_account: "sa-github@fab-benchmarks-485014.iam.gserviceaccount.com"
      - name: Terraform Apply
        env:
          TF_VAR_project_id: ${{ secrets.TF_VARS_project_id }}
        run: terraform apply -auto-approve
